export const disciplinas = [
    { id: 1, label: 'Processamento de Linguagem Natural', subtitle: 'PRG0018' },
    { id: 2, label: 'Estrutura de Dados', subtitle: 'SCC0122' },
    { id: 3, label: 'Introdução à Ciência de Computação II', subtitle: 'SCC0201' },
    { id: 4, label: 'Algoritmos e Estruturas de Dados I', subtitle: 'SCC0202' },
    { id: 5, label: 'Teoria da Computação e Linguagens Formais', subtitle: 'SCC0205' },
    { id: 6, label: 'Computadores e Sociedade I', subtitle: 'SCC0207' },
    { id: 7, label: 'Empreendedores em Informática', subtitle: 'SCC0209' },
    { id: 8, label: 'Laboratório de Algoritmos Avançados II', subtitle: 'SCC0211' },
    { id: 9, label: 'Metodologia de Pesquisa em Computação', subtitle: 'SCC0213' },
    { id: 10, label: 'Algoritmos Avançados e Aplicações', subtitle: 'SCC0218' },
    { id: 11, label: 'Introdução ao Desenvolvimento Web', subtitle: 'SCC0219' },
    { id: 12, label: 'Laboratório de Introdução à Ciência de Computação II', subtitle: 'SCC0220' },
    { id: 13, label: 'Estruturas de dados I', subtitle: 'SCC0223' },
    { id: 14, label: 'Seminários de Computação I (quinzenal)', subtitle: 'SCC0227' },
    { id: 15, label: 'Seminários de Computação III (quinzenal)', subtitle: 'SCC0229' },
    { id: 16, label: 'Inteligência Artificial', subtitle: 'SCC0230' },
    { id: 17, label: 'Aplicações de Aprendizado de Máquina e Mineração de Dados', subtitle: 'SCC0233' },
    { id: 18, label: 'Laboratório de Bases de Dados', subtitle: 'SCC0241' },
    { id: 19, label: 'Mineração a partir de Grandes Bases de Dados', subtitle: 'SCC0244' },
    { id: 20, label: 'Computação Gráfica', subtitle: 'SCC0250' },
    { id: 21, label: 'Visualização Computacional', subtitle: 'SCC0252' },
    { id: 22, label: 'Interação Humano-Computador e Experiência do Usuário', subtitle: 'SCC0260' },
    { id: 23, label: 'Introdução à Bioinformática', subtitle: 'SCC0271' },
    { id: 24, label: 'Robôs Móveis e Inteligentes', subtitle: 'SCC0273' },
    { id: 25, label: 'Introdução à Ciência de Dados', subtitle: 'SCC0275' },
    { id: 26, label: 'Competições de Ciência de Dados', subtitle: 'SCC0277' },
    { id: 27, label: 'Introdução à Web Semântica', subtitle: 'SCC0283' },
    { id: 28, label: 'Sistemas de Recomendação', subtitle: 'SCC0284' },
    { id: 29, label: 'Mineração de Dados Não Estruturados', subtitle: 'SCC0287' },
    { id: 30, label: 'Projeto de Intercâmbio I', subtitle: 'SCC0289' },
    { id: 31, label: 'Projeto de Intercâmbio II', subtitle: 'SCC0290' },
    { id: 32, label: 'Estágio Supervisionado I', subtitle: 'SCC0291' },
    { id: 33, label: 'Estágio Supervisionado II', subtitle: 'SCC0292' },
    { id: 34, label: 'Projeto de Graduação I', subtitle: 'SCC0293' },
    { id: 35, label: 'Projeto de Graduação II', subtitle: 'SCC0294' },
    { id: 36, label: 'Projeto Empreendedor I', subtitle: 'SCC0300' },
    { id: 37, label: 'Projeto Empreendedor II', subtitle: 'SCC0302' },
    { id: 38, label: 'Algoritmos e Estruturas de Dados I', subtitle: 'SCC0502' },
    { id: 39, label: 'Bases de Dados', subtitle: 'SCC0540' },
    { id: 40, label: 'Interação Humano-Computador e Experiência do Usuário', subtitle: 'SCC0560' },
    { id: 41, label: 'Acessibilidade em Sistemas Computacionais', subtitle: 'SCC0580' },
    { id: 42, label: 'Programação Orientada a Objetos', subtitle: 'SCC0604' },
    { id: 43, label: 'Estruturas de Dados III', subtitle: 'SCC0607' },
    { id: 44, label: 'Bases de Dados', subtitle: 'SCC0640' },
    { id: 45, label: 'Laboratório de Bases de Dados', subtitle: 'SCC0641' },
    { id: 46, label: 'Computação Gráfica', subtitle: 'SCC0650' },
    { id: 47, label: 'Tópicos Avançados em Ciências de Computação I - Aprendizado de Máquina para Séries Temporais', subtitle: 'SCC0910' },
    { id: 48, label: 'Tópicos Avançados em Ciências de Computação I - Redes Complexas para Ciências da Computação', subtitle: 'SCC0910' },
    { id: 49, label: 'Tópicos Avançados em Ciências de Computação II - Computação Bioinspirada', subtitle: 'SCC0911' }
];

export const docentes = [
    { id: 1, label: 'Thiago Alexandre S. Pardo' },
    { id: 2, label: 'André de Freitas Smaira' },
    { id: 3, label: 'Diego Raphael Amancio' },
    { id: 4, label: 'Marcelo Garcia Manzato' },
    { id: 5, label: 'Rudinei Goularte' },
    { id: 6, label: 'Joao Luis Garcia Rosa' },
    { id: 7, label: 'Renato Moraes Silva' },
    { id: 8, label: 'Bruna Carolina R. da Cunha' },
    { id: 9, label: 'Solange Oliveira Rezende' },
    { id: 10, label: 'João do Espírito Santo B. Neto' },
    { id: 11, label: 'Agma Juci Machado Traina' },
    { id: 12, label: 'Maria Cristina F. Oliveira' },
    { id: 13, label: 'Alneu de Andrade Lopes' },
    { id: 14, label: 'Diego Furtado Silva' },
    { id: 15, label: 'José Fernando Rodrigues Junior' },
    { id: 16, label: 'Caetano Traina Jr' },
    { id: 17, label: 'Jean Roberto Ponciano' },
    { id: 18, label: 'Kamila Rios da Hora Rodrigues' },
    { id: 19, label: 'Ricardo Cerri' },
    { id: 20, label: 'Roseli Ap. Francelin Romero' },
    { id: 21, label: 'Ricardo Marcondes Marcacini' },
    { id: 22, label: 'Moacir Antonelli Ponti' },
    { id: 23, label: 'Elaine Parros Machado de Sousa' },
    { id: 24, label: 'Dilvan de Abreu Moreira' },
];