name: Firebase Web CI

on: push

jobs:
  Build_Deploy_Web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      ## Checkout current branch
      - uses: actions/checkout@v1

      ## Setup node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      ## Install dependencies
      - name: yarn install
        run: |
          yarn
      ## Test
      - name: Run tests
        run: |
          CI=true yarn test
      ## Build & Deploy
      - name: Build & Deploy
        run: |
          yarn build
          firebase deploy --only hosting --token ${{ SECRETS.FIREBASE_TOKEN }} 
