name: Firebase CI
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install Yarn
        run: curl -o- -L https://yarnpkg.com/install.sh | bash

      - name: Checkout Repo
        uses: actions/checkout@master
      
      - name: Install Functions Dependencies
        working-directory: functions
        run: yarn

      - name: Deploy to Firebase
        run: npx firebase-tools deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
